#!/bin/bash
cd $HOME
clear
echo ""
echo -e "\033[0;34m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
echo -e "\E[41;1;37m            • PACOTE FREE •             \E[0m"
echo -e "\033[0;34m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
echo -e "\033[0m\033[01;37m(1) \033[01;33mToken padrão\033[0m"
echo -e "\033[0m\033[01;37m(2) \033[01;33mTestar Token personalizado \033[0m"

echo -e "\033[0m\033[01;37m(3) \033[01;33m JOKER PO DE NET \033[0m"


echo -e "\033[0m\033[01;37m(4) \033[01;33mSair\033[0m"
echo -e "\033[0;34m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
echo " "
echo -e "\033[1;32m O QUE DESEJA FAZER \033[1;33m?\033[1;31m?\033[1;37m : "
read OPTION

case $OPTION in
        (1) 
        curl -sO https://raw.githubusercontent.com/termuxmarlon/netfree/main/mbsfree1 && chmod 777 mbsfree1 && ./mbsfree1
        ;;
        (2) 
        curl -sO https://raw.githubusercontent.com/termuxmarlon/netfree/main/mbsfree2 && chmod 777 mbsfree2 && ./mbsfree2
        ;;
        (3)  
       curl -sO https://raw.githubusercontent.com/termuxmarlon/netfree/main/ganharcreditos && chmod 777 mbsfree2 && ./mbsfree2
;;
        (4)
        clear
        exit;
        ;;
        (*) echo -e "\033[1;31mOpção invalida\033[1;37m"

   esac
