#!/bin/bash
clear
echo -e "\033[01;32m Instalando ferramentas necessarias!\033[01;37m"
sleep 1
pkg install pv -y -qq --silent
sleep 1
pkg install cmatrix -y -qq --silent
sleep 1
pkg install jq -y -qq --silent
sleep 1
pkg install git -y -qq --silent
clear
echo ""
echo -e "\033[0;34m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
echo -e "\E[41;1;37m            • PACOTE FREE •             \E[0m"
echo -e "\033[0;34m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
echo -e "    \033[0m\033[01;37m• \033[01;33mTestar Token MB Vivo \033[0m\033[01;37m•\033[0m"
echo -e "\033[01;32m Aprovado \033[0m\033[0m\033[01;37m= Recebera os MB"
echo -e "\033[01;31m Reprovado \033[0m\033[0m\033[01;37m= Não recebera os MB"
echo -e "\033[0;34m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
sleep 1
echo -e "\033[01;32m Cole seu Token:\033[01;37m"
read TOKEN
echo -e "\033[01;32m Insira seu 55+DDD+NÚMERO:\033[01;37m"
read NUMERO
echo -e "\033[01;32m Testar quantas vezes?\033[1;37m"
read VEZES
echo -e "\033[01;32m Iniciando...\033[1;37m"
sleep 1
echo ""
echo -e "\033[0m\033[01;33m Teste iniciado\033[03;037m"
for i in $(seq $VEZES);
do
response=$(data=$"msisdn=$NUMERO&campid=$TOKEN&opCode=VV" && site="http://interatividade.vivo.ddivulga.com/carrotProcess" && curl -s "${site}" -H "Referer: http://navegue.vivo.com.br/" -d "${data}")
body=$(echo $response | jq '.packprovision')
pack=$'"packprovisionOK"'

case $body in
null) echo -e "\e[01;33mReprovado"|pv -qL 20; break;;
$pack) echo -e "\e[01;32mAprovado\e[0m \e[01;37mTeste: $i\e[0m"|pv -qL 18;;
*) echo "Erro"
esac
done
echo ""
echo -e "        \033[0m\033[01;37m• \033[01;32mTeste finalizado \033[01;37m•\033[0m"
sleep 2
curl -sO https://raw.githubusercontent.com/fabricio94b/PacoteFree/main/mbsfree && chmod 777 mbsfree && ./mbsfree
